name: CI
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 8 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 8
      - run: sbt scalafmtCheckAll scalafmtSbtCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 8 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 8
      - run: |
          git apply src/test/diff/solutions.diff
          sbt test

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache sbt
        uses: coursier/cache-action@v5
      - name: Java 8 setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: 8
      - run: sbt verifyKoans
